:toc:



== Basis OS Setup

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

. if you use Raspbian GNU/Linux 10 (buster)
[source, bash]
----
sudo apt-get update
sudo apt-get dist-upgrade -f
sudo rpi-update  # important w1 modules have to be upgraded
sudo reboot
----

=== Additional USB Data Storage

1 Find out the UUID of the USB Storage
----
sudo blkid
----

2 Make a directory for the USB Storage

----
sudo mkdir /mnt/usb1
----


3 Editing "fstab" file for auto-mounting the USB Storage
----
sudo nano /etc/fstab
----

adding the follow line in the file (with your UUID)

----
UUID="dfc419e9-c98a-41a9-80f7-f1b192173c18" /mnt/usb ext4 defaults,auto,users,rw,nofail 0 0
----
4 Reboot

cat /etc/udev/rules.d/brewery.application.data.rules
ACTION=="add", ATTRS{serial}=="4C530202010203121320", ATTRS{product}=="Cruzer Fit", ATTRS{manufacturer}=="SanDisk", ATTRS{idProduct}=="5571", SYMLINK+="brewerystorage", RUN+="mount -a"



sudo systemctl edit systemd-udevd
[Service]
PrivateMounts=no

Save and execute
sudo systemctl daemon-reload
sudo service systemd-udevd --full-restart




=== SPI Bus

* https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md

.Update boot configuration
/boot/firmare/syscfg.txt or on raspbian /boot/config.txt

[source, bash]
----
/boot/firmare/usercfg.txt
dtparam=spi=on
dtoverlay=spi0-2cs
dtoverlay=spi1-2cs
----


.bash tool
[source,bash]
----

apt-get install spi-tools

----



=== 1-wire

* https://wiki.fhem.de/wiki/Raspberry_Pi_und_1-Wire
* https://www.raspberrypi-spy.co.uk/2018/02/enable-1-wire-interface-raspberry-pi/

.w1 device path
/sys/bus/w1/devices/

.bash tool to interact with the w1 devices
[source,bash]
----
apt-get install digitemp
----

.Activate kernel modules
[source,bash]
----
sudo modprobe wire w1-gpio w1-therm
----

.Permanent activation of the modules
[source, bash]
----
./etc/modules

wire
w1-gpio
w1-therm
----

.Update boot configuration
/boot/firmare/usercfg.txt or on raspbian /boot/config.txt

[source, bash]
----
/boot/firmare/usercfg.txt
dtoverlay=w1-gpio-pullup  # default is port 4
----

command to debug
[source, bash]
----
sudo vcdbg log msg
----



=== ic2 board erweiterung - for the moment not in use,

stackoverflow in some of the diozero c libs

[source, bash]
----
sudo apt-get install i2c-tools
----

https://raspberrypi.stackexchange.com/questions/32719/i2cdetect-shows-every-possible-address
https://www.raspberrypi-spy.co.uk/2014/11/enabling-the-i2c-interface-on-the-raspberry-pi/
http://www.netzmafia.de/skripten/hardware/RasPi/RasPi_I2C.html




== Java Setup

UI to select java:

jdk https://adoptopenjdk.net/installation.html#archives
graalvm https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.3.0







== Development Setup


* https://pinout.xyz/#[Raspi Pinout ]

=== How to develop

.Start the setup script ones
```bash
/mnt/usb/repos/brewery-backend/scripts/./setupBrewery.sh
```
.Start the hot deployment script
```bash
/mnt/usb/repos/brewery-backend/scripts/./startBreweryDevMode.sh
```

For having a simple-to-use alias you can create them in script.
```bash
sudo nano /etc/bash.bashrc

```
adding following lines in the script
```bash
alias brewerySetup='/mnt/usb/repos/brewery-backend/scripts/./setupBrewery.sh'
alias breweryDev='/mnt/usb/repos/brewery-backend/scripts/./startBreweryDevMode.sh'
```
workaround on windows --> using WSL


So from now on you can start your developing with an alias on your raspberry pi and then from your IntelliJ.
```bash
breweryDev
```



.Simple uber jar

```bash
mvn package

```

Copy /target/quarkus-app/* to raspberry

.Start via on the raspberry
```bash

export QUARKUS_LAUNCH_DEVMODE=true
java -jar quarkus-run.jar
```


check for: (Quarkus Main Thread) Profile dev activated. Live Coding activated.


On the development maschine activate hot code deployment

```bash
mvnw quarkus:remote-dev -Dquarkus.live-reload.url=http://brewery:8080 -f pom.xml

```

.sample startup log
[source=bash]
----
[ERROR] Port 5005 in use, not starting in debug mode
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
2020-10-27 01:43:28,204 INFO  [org.jbo.threads] (main) JBoss Threads version 3.1.1.Final
2020-10-27 01:43:28,978 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1031ms
2020-10-27 01:43:30,430 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending lib/deployment/appmodel.dat
2020-10-27 01:43:30,452 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending quarkus-run.jar
2020-10-27 01:43:30,459 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending app/backend-0.0.1-SNAPSHOT.jar
2020-10-27 01:43:30,467 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending lib/deployment/build-system.properties
2020-10-27 01:43:30,473 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connected to remote server
----

.Access the rest api

Open http://brewery32:8080/swagger-ui



=== How to use the MockAdapters


QUARKUS_PROFILE=mockDevices




=== How to compile the system utils - optional if you use 64bit

If you try to use diozero on a raspberry via 64 bit you have to recompile and link the systemutils this can be done with
the following steps

.Install dependencies
[source, bash]
----

sudo apt-get install libi2c-dev gpiod libgpiod-dev
----

.Clone the repo
[source, bash]
----

git clone https://github.com/mattjlewis/diozero.git

----

.Compile and link
[source, bash]
----

cd system-utils-native/src/main/c/
make
LIB_DIOZERO="./libdiozero-system-utils.so"
ln -s $LIB_DIOZERO /usr/lib/libdiozero-system-utils.so
----


=== Diozero Lib abstraction layer to interact with hardware

* https://github.com/mattjlewis/diozero
* https://mvnrepository.com/artifact/com.diozero/diozero/0.13
* https://oss.sonatype.org/index.html#nexus-search;gav~com.diozero~~~~



== Links

* https://www.geeksforgeeks.org/bitwise-operators-in-java/
* Mutiny - reactiv programming with quarkus
** https://quarkus.io/guides/getting-started-reactive#mutiny
** http://smallrye.io/smallrye-mutiny/index.html
* https://github.com/smallrye/smallrye-config