quarkus:
  package:
    type: mutable-jar
  live-reload:
    password: changeit
    url: http://brewery:8080

#quarkus.package.type=mutable-jar
#quarkus.live-reload.password=changeit
#quarkus.live-reload.url=http://brewery:8080


brewery:
  inpot:
    w1-temp-device-path: "/sys/bus/w1/devices/w1_bus_master1/"
    w1-temp-top-id: "012033890289"
    w1-temp-middle-id: "012033b5c85b"
    w1-temp-bottom-id: "01203389483c"
  controlcabinet:
    w1-air-temp-id: "012033c6d23a"
    w1-air-temp-in-cabinet-id: "012033c43620"
    w1-temp-device-path: "/sys/bus/w1/devices/w1_bus_master1/"
  collector:
    base-collection-intervall-in-ms: 10
    input-collection-intervall-in-ms: 20
    temperature-collection-intervall-in-ms: 2000
    ui-update-intervall-in-ms: 2000
    calculation-intervall-in-ms: 150
    persistence-intervall-in-ms: 4000
  spi:
    extensionboard:
      led1:
        mcpNumber: 2
        port: B
        pin: 1
      beep:
        mcpNumber: 2
        port: B
        pin: 1
      gfa230-v-relais:
        mcpNumber: 1
        port: B
        pin: 1
      motor1Pul:
        mcpNumber: 1
        port: B
        pin: 3
      motor1Dir:
        mcpNumber: 1
        port: B
        pin: 5
      motor1En:
        mcpNumber: 1
        port: B
        pin: 7



# mockDevices
#"%mockDevices":
#  brewery:
#    inpot:
#      use-mock: true