# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    
#on:
#  workflow_dispatch:
#  push:

jobs:
  build:

    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 armv7
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 
      
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu20.04

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)

    - name: Get the output
      # Echo the `uname` output parameter from the `runcmd` step test
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
