# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 armv7
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu20.04

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            export JAVA_HOME=${PWD}/jdk-11.0.9.1+1
            export PATH=$JAVA_HOME/bin:$PATH
            chmod +x gradlew
            ./gradlew build


          install: |
            apt update -y
            apt install wget -y
            wget --no-check-certificate "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_arm_linux_hotspot_11.0.9.1_1.tar.gz"
            tar -xzf OpenJDK11U-jdk_arm_linux_hotspot_11.0.9.1_1.tar.gz

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step test
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"